CMD_START = "🏠 Главное меню"
CMD_NOW = "⏰ Что сейчас?"
CMD_TODAY = "📅 Расписание на сегодня"
CMD_TOMORROW = "📆 Расписание на завтра"
CMD_WEEK = "📋 Расписание на неделю"
CMD_SETTINGS = "⚙️ Настройки"
CMD_HELP = "📖 Помощь"
